### ISSUE TITLE
Handle multi-lines log entry with common prefix

### ISSUE THREAD

**Issue by swordsp** [SumoLogic/sumoshell#23]
```
2017-01-28 17:59:50  Exception in thread "main" java.lang.NullPointerException
2017-01-28 17:59:50          at com.example.myproject.Book.getTitle(Book.java:16)
2017-01-28 17:59:50          at com.example.myproject.Author.getBookTitles(Author.java:25)
2017-01-28 17:59:50          at com.example.myproject.Bootstrap.main(Bootstrap.java:14)

```

For now sumoshell cannot recognize the above log lines as a same log entry.

**Comment by rcoh** [comment]
Interesting. This isn't a common logging pattern I've seen before. I'll
think about how to handle it - I would also accept a pull request

**Comment by swordsp** [comment]
We have a agent process to collect logs from different applications on multiple servers, and the prefix is actually appended by that agent which contains fields like timestamp/hosts/container id/etc.

I'll take a look at the code and see if I could send out a patch.
